apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: myapp-replicasets
  labels:
    app: myapp
spec:
  selector: 
    matchLabels:
      env: myapp
  replicas: 4
  template: 
    metadata:
      name: redis
      labels:
        env: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
        